robot_radius: 0.15

transform_tolerance: 0.4
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 20
 raytrace_range: 20
 inflation_radius: 0.1
 track_unknown_space: false
 combination_method: 1

 observation_sources: laser_scan_sensor
 laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true, sensor_frame: base_scan}


inflation_layer:
  enabled:              true
  cost_scaling_factor:  3.0  
  inflation_radius:     0.1

static_layer:
  enabled:              true
  map_topic:            "map"

